futurice/haskell-mega-repo

- README.md
- env-config/env-config.cabal
- env-config/package.yaml
- futuhours-api/futuhours-api.cabal
- futuhours-api/package.yaml
- futuhours-api/src/Data/BinaryFromJSON.hs
- futuhours-api/src/Data/Time/Fxtra.hs
- futuhours-api/src/Database/PostgreSQL/Simple/Fxtra.hs
- futuhours-api/src/Distribution/Server/Framework/Cron.hs
- futuhours-api/src/Futurice/App/FutuHours.hs
- futuhours-api/src/Futurice/App/FutuHours/API.hs
- futuhours-api/src/Futurice/App/FutuHours/Config.hs
- futuhours-api/src/Futurice/App/FutuHours/Context.hs
- futuhours-api/src/Futurice/App/FutuHours/DecayCache.hs
- futuhours-api/src/Futurice/App/FutuHours/Endpoints.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanMill.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanMillCache.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanMillUserIds.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanmillCacheDataSource.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanmillDataSource.hs
- futuhours-api/src/Futurice/App/FutuHours/Precalc.hs
- futuhours-api/src/Futurice/App/FutuHours/Reports/MissingHours.hs
- futuhours-api/src/Futurice/App/FutuHours/Timereports.hs
- futuhours-api/src/Futurice/App/FutuHours/Tools.hs
- futuhours-api/src/Futurice/App/FutuHours/Types.hs
- futuhours-api/src/Futurice/ExpFit.hs
- futuhours-api/src/Servant/Futurice.hs
Use it in `env-config` and `futuhours-api`
> Add note about `default-extension`

- futuhours-api/src/Futurice/App/FutuHours/PlanmillCacheDataSource.hs
- futuhours-api/src/Futurice/App/FutuHours/PlanmillDataSource.hs
- planmill-client/src/PlanMill/Endpoints.hs
- planmill-client/src/PlanMill/Eval.hs
- planmill-client/src/PlanMill/Queries.hs
- planmill-client/src/PlanMill/Types/Query.hs
- planmill-client/src/PlanMill/Types/Request.hs
- planmill-client/src/PlanMill/Types/ResultInterval.hs
> Change planmill-client QueryString to Map Text Text

- futuhours-api/src/Futurice/App/FutuHours/Endpoints.hs
- futuhours-api/src/Futurice/App/FutuHours/Reports/MissingHours.hs
- futuhours-api/src/Futurice/App/FutuHours/Types.hs
- futurice-integrations/futurice-integrations.cabal
- futurice-integrations/package.yaml
- planmill-client/src/PlanMill/Internal/Prelude.hs
- planmill-client/src/PlanMill/Types/TimeBalance.hs
- planmill-client/src/PlanMill/Types/Timereport.hs
- planmill-client/src/PlanMill/Types/UserCapacity.hs
- stack-ghc-8.0.yaml
> Use NDT - time units

- futuhours-api/src/Futurice/App/FutuHours.hs
- futuhours-api/src/Futurice/App/FutuHours/API.hs
- futuhours-api/src/Futurice/App/FutuHours/Endpoints.hs
- futuhours-api/src/Futurice/App/FutuHours/Types.hs
> Remove /balances from futuhours-api

- futuhours-api/src/Futurice/App/FutuhoursApi/Types.hs
- reports-app/src/Futurice/App/Reports/GithubIssues.hs
- reports-app/src/Futurice/App/Reports/MissingHours.hs
- spice-stats/src/Futurice/App/Spice/Types.hs
> Add sopToEncoding to rest of the instances

- checklist-app/checklist-app.cabal
- checklist-app/checklist.js
- checklist-app/import/Import.hs
- checklist-app/package.yaml
- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/API.hs
- checklist-app/src/Futurice/App/Checklist/Clay.hs
- checklist-app/src/Futurice/App/Checklist/Command.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Pages/CreateEmployee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/CreateTask.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Index.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Tasks.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
- checklist-app/src/Futurice/App/Checklist/Types/TaskAppliance.hs
- checklist-app/tests/Tests.hs
- stack-ghc-8.0.yaml
- stack-lts-6.yaml
> Checklist polish

- checklist-app/checklist-app.cabal
- checklist-app/checklist.js
- checklist-app/import/Import.hs
- checklist-app/package.yaml
- checklist-app/src/Futurice/App/Checklist/Command.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Pages/CreateTask.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Tasks.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
- checklist-app/src/Futurice/App/Checklist/Types/World.hs
> Checklist mon 2017 01 23

- checklist-app/checklist-app.cabal
- checklist-app/import/Import.hs
- checklist-app/package.yaml
- env-config/src/Futurice/EnvConfig.hs
- futurice-servant/src/Futurice/Servant.hs
- github-proxy/cli/Main.hs
- planmill-client/cli2/Main.hs
- planmill-proxy/cli/Main.hs
- spice-stats/cli/Main.hs
> [env-config] more general getConfig signature

- planmill-client/cli/Caching.hs
- planmill-client/cli/Main.hs
- planmill-client/fixtures/project.json
Small improvement to cli tool to use current user/env.
> planmill-client CLI improvements

- .travis.yml
- email-proxy/email-proxy.cabal
- email-proxy/package.yaml
- futurice-github/src/Futurice/GitHub.hs
- sms-proxy/package.yaml
- sms-proxy/sms-proxy.cabal
- sms-proxy/src/Futurice/App/SmsProxy.hs
- sms-proxy/src/Futurice/App/SmsProxy/Config.hs
- sms-proxy/src/Futurice/App/SmsProxy/Ctx.hs
- sms-proxy/src/Futurice/App/SmsProxy/Logic.hs
SMS support for legacy API using Twilio.
> Twilio for SMS

- hours-api/src/Futurice/App/HoursApi.hs
- hours-api/src/Futurice/App/HoursApi/Logic.hs
Fixes https://github.com/futurice/hours-ui/issues/70
> Delete>>Create on edit, if task id changes

- hours-api/src/Futurice/App/HoursApi/Logic.hs
Fixes https://github.com/futurice/hours-ui/issues/71
> Seems we always need to divide by 7.5

- personio-client/fixtures/employee.json
- personio-client/src/Personio/Types.hs
- personio-client/tests/Tests.hs
Supervisor id, work-phone, email and primary-role added to Employee type.
> Personio tests

- personio-client/fixtures/employee-m-email.json
- personio-client/fixtures/employee-m-office.json
- personio-client/fixtures/employee-m-phone.json
- personio-client/fixtures/employee-m-role.json
- personio-client/fixtures/employee-m-tribe.json
- personio-client/src/Personio/Types.hs
- personio-client/tests/Tests.hs
Validating constCenter, tribe, office, phone, role and email.
> Personio validation several

- personio-client/fixtures/employee-i-iban.json
- personio-client/fixtures/employee-m-iban.json
- personio-client/src/Personio/Types.hs
- personio-client/tests/Tests.hs
This solution lacks Applicative-stuff and Functors since I do not fully understand them but it works.
> employee invalid iban PR

- personio-client/fixtures/employee-i-login.json
- personio-client/src/Personio/Types.hs
- personio-client/tests/Tests.hs
Login validation. Branch login-personio-validation-login-pr was branched from current master.
> Personio validation login pr

- proxy-app/src/Futurice/App/Proxy.hs
- proxy-mgmt-app/schema.psql
- Altered credentials-table
- updated checkCreds
> Proxy app acl

- proxy-app/src/Futurice/App/Proxy.hs
When accessing swagger-ui via proxy-app, it now requires only correct username and password-combination. 
Otherwise works like before.
Tried to make it as readable as possible.
> endpoint 'swagger-ui/' does not require endpoint-check

- contacts-api/contacts-api.cabal
- contacts-api/package.yaml
- contacts-api/src/Futurice/App/Contacts/Logic.hs
- personio-client/src/Personio/Types.hs
Progress so far. How does it look?
> Contacts-api use Personio-client

- contacts-api/src/Futurice/App/Contacts/Logic.hs
- contacts-api/src/Futurice/App/Contacts/Types.hs
- futurice-tribes/futurice-tribes.cabal
- futurice-tribes/package.yaml
- futurice-tribes/src/Futurice/Office.hs
- futurice-tribes/src/Futurice/Tribe.hs
- personio-client/src/Personio/Types.hs
- Add position to Personio.Employee
- truncate long flowdock nicks
- add csv instances to Futurice.Office and .Tribe
> Contacts refactor

- hours-api/src/Futurice/App/HoursApi/Class.hs
- hours-api/src/Futurice/App/HoursApi/Logic.hs
- hours-api/src/Futurice/App/HoursApi/Monad.hs
- hours-api/src/Futurice/App/HoursApi/Types.hs
- hours-api/src/Futurice/App/HoursMock/MockData.hs
- hours-api/src/Futurice/App/HoursMock/Monad.hs
- planmill-client/README.md
- planmill-client/fixtures/absence.json
- planmill-client/src/PlanMill/Queries.hs
- planmill-client/src/PlanMill/Types/Absence.hs
- planmill-client/src/PlanMill/Types/Enumeration.hs
- planmill-client/src/PlanMill/Types/ReportableAssignment.hs
- planmill-client/src/PlanMill/Types/Task.hs
- proxy-app/tests/Tests.hs
Check if task is absence task and if it is change the name to absence reason. Convert should be enumeration call, but couldn't think of clean way to do it
> Add absence reason to absence task names

- checklist-app/checklist-app.cabal
- checklist-app/checklist.js
- checklist-app/import/Import.hs
- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/API.hs
- checklist-app/src/Futurice/App/Checklist/Command.hs
- checklist-app/src/Futurice/App/Checklist/Logic.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Pages/CreateEmployee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/CreateTask.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Personio.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Tasks.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
- checklist-app/src/Futurice/App/Checklist/Types/TaskTag.hs
Add way to tag tasks. Also highlight if personio information is different than checklist info
> Checklist improvements

- hours-api/src/Futurice/App/HoursApi/Logic.hs
- hours-api/src/Futurice/App/HoursApi/Monad.hs
- planmill-client/src/PlanMill/Endpoints.hs
Requesting absencecs for user drops from 7.667166s to 2.637219s
> Add absencesFromIntervalFor

- build-in-linux-cabal.sh
- mega-repo-tool/README.md
- mega-repo-tool/src/Futurice/App/MegaRepoTool/BuildDocker.hs
Fix the size of short git hash to ensure combability between different git versions
> Fix the size of short git hash

- checklist-app/checklist-app.cabal
- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Config.hs
- checklist-app/src/Futurice/App/Checklist/Ctx.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Index.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
Add Github and maybe some other integrations to app
> Checklist integrations

- checklist-app/checklist-app.cabal
- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/API.hs
- checklist-app/src/Futurice/App/Checklist/Charts/Done.hs
- checklist-app/src/Futurice/App/Checklist/Logic.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Archive.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Report.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Stats.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
- checklist-app/src/Futurice/App/Checklist/Types/SortCriteria.hs
- checklist-app/src/Futurice/App/Checklist/Types/World.hs
Stats page where you can see completion rates for active, archived and active + archived employees for each task
> Checklist stats

- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Stats.hs
- checklist-app/src/Futurice/App/Checklist/Types/SortCriteria.hs
Separate active employees depending on if their due date is in future or in past. Also fix for archived employee counting
> Separate active employees based on due date

- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Index.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Types/TaskTag.hs
Tag to use to display job offer accepted status and email contact
> Add FirstContact tag

- checklist-app/src/Futurice/App/Checklist.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Employee.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Index.hs
- checklist-app/src/Futurice/App/Checklist/Pages/Task.hs
- checklist-app/src/Futurice/App/Checklist/Types.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
IntegrationData type for carrying data from external source. Also when showing HR number, first check checklist, then personio
> Refactor external data to single data type and check cl hrnumber 1st

- cabal.project
- mega-repo-tool.config
- personio-proxy/LICENSE
- personio-proxy/README.md
- personio-proxy/Setup.hs
- personio-proxy/personio-proxy.cabal
- personio-proxy/src/Futurice/App/PersonioProxy.hs
- personio-proxy/src/Futurice/App/PersonioProxy/API.hs
- personio-proxy/src/Futurice/App/PersonioProxy/Config.hs
- personio-proxy/src/Futurice/App/PersonioProxy/Logic.hs
- personio-proxy/src/Futurice/App/PersonioProxy/Types.hs
- personio-proxy/srv/Main.hs
Should have the same functionality as the fum-carbon persionio API has. Anything missing?
> Extract Personio proxy from fum-carbon

- mega-repo-tool/mega-repo-tool.cabal
- mega-repo-tool/src/Futurice/App/MegaRepoTool/GenPass.hs
Hopefully I understood this correctly ^^'
> Generate password with help of base64-bytestring

- planmill-client/cli2/Main.hs
- planmill-client/planmill-client.cabal
- planmill-client/src/PlanMill/Endpoints.hs
- planmill-client/src/PlanMill/Types.hs
- planmill-client/src/PlanMill/Types/Hook.hs
- planmill-client/src/PlanMill/Types/Inserted.hs
* read, add, delete Hooks (with pm-cli)
> PlanMill Hooks support

- fum-carbon-app/fum-carbon-app.cabal
- fum-carbon-app/src/Futurice/App/FUM/API.hs
- fum-carbon-app/src/Futurice/App/FUM/Machine.hs
- personio-client/personio-client.cabal
- personio-client/src/Personio/Types.hs
- personio-client/src/Personio/Types/ScheduleEmployee.hs
- personio-proxy/src/Futurice/App/PersonioProxy.hs
- personio-proxy/src/Futurice/App/PersonioProxy/API.hs
- personio-proxy/src/Futurice/App/PersonioProxy/Logic.hs
Also added employeeId to payload for later use. Remember to update Schedule url before moving this change to production
> Move schedule-info endpoint from fum-carbon to personio-proxy

- library-app/schema.sql
I wrote some pseudo code, and noticed few things (see my commit).
> Library schema

- futurice-constants/src/Futurice/Constants.hs
- library-app/library-app.cabal
- library-app/library-app.js
- library-app/src/Futurice/App/Library.hs
- library-app/src/Futurice/App/Library/API.hs
- library-app/src/Futurice/App/Library/Logic.hs
- library-app/src/Futurice/App/Library/Pages/AddItemPage.hs
- library-app/src/Futurice/App/Library/Types/AddItemRequest.hs
- library-app/src/Futurice/App/Library/Types/BookInformation.hs
- library-app/src/Futurice/App/Library/Types/BookInformationByISBNResponse.hs
- library-app/src/Futurice/App/Library/Types/BookInformationResponse.hs
- sisosota-client/sisosota-client.cabal
- sisosota-client/src/Futurice/App/Sisosota/Types.hs
Some validations for form data and finally switching to use Sisosota as cover picture source. I
> Library use sisosota

- library-app/library-app.cabal
- library-app/library-app.js
- library-app/src/Futurice/App/Library.hs
- library-app/src/Futurice/App/Library/Config.hs
- library-app/src/Futurice/App/Library/Logic.hs
- library-app/src/Futurice/App/Library/Pages/AddItemPage.hs
- library-app/src/Futurice/App/Library/Types.hs
- library-app/src/Futurice/App/Library/Types/AddItemRequest.hs
- library-app/src/Futurice/App/Library/Types/BookInformationByISBNResponse.hs
Add Item Page Magic button first searches from database based on ISBN and then searches Amazon.
> Search books from Amazon with ISBN

- library-app/library-app.js
- library-app/src/Futurice/App/Library.hs
- library-app/src/Futurice/App/Library/API.hs
- library-app/src/Futurice/App/Library/Logic.hs
- library-app/src/Futurice/App/Library/Markup.hs
- library-app/src/Futurice/App/Library/Pages/BookInformationPage.hs
- library-app/src/Futurice/App/Library/Pages/IndexPage.hs
- library-app/src/Futurice/App/Library/Types.hs
- library-app/src/Futurice/App/Library/Types/AddItemRequest.hs
- library-app/src/Futurice/App/Library/Types/Library.hs
- library-app/src/Futurice/App/Library/Types/Loan.hs
- library-app/tests/Tests.hs
Add way to filter based on library and availability and add way to do snatch aka forced loan on item
> Library add more filtering + forced loan

- library-app/library-app.js
- library-app/src/Futurice/App/Library.hs
- library-app/src/Futurice/App/Library/API.hs
- library-app/src/Futurice/App/Library/Logic.hs
- library-app/src/Futurice/App/Library/Pages/BookInformationPage.hs
- library-app/src/Futurice/App/Library/Pages/EditItemPage.hs
- library-app/src/Futurice/App/Library/Types.hs
- library-app/src/Futurice/App/Library/Types/AddItemRequest.hs
- library-app/src/Futurice/App/Library/Types/BoardGameInformation.hs
- library-app/src/Futurice/App/Library/Types/BookInformation.hs
- library-app/src/Futurice/App/Library/Types/BorrowRequest.hs
- library-app/src/Futurice/App/Library/Types/Library.hs
- library-app/src/Futurice/App/Library/Types/Loan.hs
- mega-repo-tool.config
Add way to add physical books to library and clean up code
> Library improvements

- futurice-servant/src/Futurice/MessageQueue.hs
- library-app/library-app.cabal
- library-app/src/Futurice/App/Library.hs
- library-app/src/Futurice/App/Library/API.hs
- library-app/src/Futurice/App/Library/Config.hs
- library-app/src/Futurice/App/Library/Logic.hs
- library-app/src/Futurice/App/Library/Pages/BoardGameInformationPage.hs
- library-app/src/Futurice/App/Library/Remainder.hs
- library-app/src/Futurice/App/Library/Reminder.hs
Current idea is, when sendRemainder is launched, it checks which loans are 30 days and over and have loantime `mod` 30 == 0. This is so that it doens't have to keep track which was the last time it send remainders to not spam people too much. Idea would be that this is launched once everyday.
If this sounds good then, next question is what next? I probably need to at this as Service? And what kind of authentication should I put here?
> Library remainder

- planmill-proxy/src-cache/Futurice/Lambda/PlanMillProxy/Cache.hs
One can say (locally):
```
mega-repo-tool lambda -l 40 PlanMillProxyCacheUpdate 5
```
so the lambda will be given 40 seconds, and update 5 items.
*NOTE* doesn't work on OSX yet
> Improve PlanMill cache updater

- planmill-client/cli/Caching.hs
- planmill-client/cli2/Main.hs
- planmill-client/planmill-client.cabal
- planmill-client/src/Control/Monad/PlanMill.hs
- planmill-client/src/PlanMill/Endpoints.hs
- planmill-client/src/PlanMill/Queries.hs
- planmill-client/src/PlanMill/Types.hs
- planmill-client/src/PlanMill/Types/Query.hs
- planmill-client/src/PlanMill/Types/Report.hs
- proxy-app/tests/Tests.hs
- reports-app/reports-app.cabal
- reports-app/src/Futurice/App/Reports.hs
- reports-app/src/Futurice/App/Reports/API.hs
- reports-app/src/Futurice/App/Reports/Markup.hs
- reports-app/src/Futurice/App/Reports/PowerAllRevenues.hs
I will clean a little bit of this before putting it into prod, but comment if you have suggestions :) At least the AllRevenuesPortfolio FromJSON part is ugly, but didn't have idea how to make it better withouth too much complications
> Add All Revenues Report data for Power

- library-app/src/Futurice/App/Library/Pages/BookInformationPage.hs
Adds the info URL to the book info page.
> Add info link to book details

- stack.yaml
- stack.yaml.lock
> Update stack.yaml to fix stack builds for HIE

- mega-repo-tool/src/Futurice/App/MegaRepoTool.hs
Adds a check that makes sure GPG2 is available, and quits early with an error if its not.
> mega-repo-tool checks for gpg2 on startup

- power-client/src/Power/API.hs
- reports-app/src/Futurice/App/Reports/API.hs
- reports-app/src/Futurice/App/Reports/OKRCompetencies.hs
Some changes were requested to the OKR report, and have been implemented accordingly.
> Requested changes to OKR competences report

- futurice-tribes/src/Futurice/Email.hs
- planmill-sync/src/Futurice/App/PlanMillSync/IndexPage.hs
- planmill-sync/src/Futurice/App/PlanMillSync/Markup.hs
Change email checking to new standard where it should be same as in Personio. Also improve layout for big screens and make getting emails
a little easier
> Checking changes and other small improvements

- futurice-servant/src/Futurice/MessageQueue.hs
- periocron/src/Futurice/Periocron.hs
- planmill-proxy/planmill-proxy.cabal
- planmill-proxy/src-cache-slow/Futurice/Lambda/PlanMillProxy/CacheSlow.hs
- planmill-proxy/src/Futurice/App/PlanMillProxy.hs
- planmill-proxy/src/Futurice/App/PlanMillProxy/Logic/UpdateAbsences.hs
Code is terrible but will be cleaned up after testing that this works
> Move absence updating from lambda to planmill-proxy 

- reports-app/src/Futurice/App/Reports/ValueCreation.hs
Convert PlanMill's "FirstName,LastName" identifier to PersonioId.
> Add PersonioId to Value Creation report

- checklist-app/src/Futurice/App/Checklist/Ctx.hs
- checklist-app/src/Futurice/App/Checklist/Markup.hs
- checklist-app/src/Futurice/App/Checklist/Types/Basic.hs
- futurice-integrations/src/Futurice/Integrations/Common.hs
- futurice-integrations/src/Futurice/Integrations/Monad/StateSet.hs
- futurice-tribes/futurice-tribes.cabal
- futurice-tribes/src/Futurice/Email.hs
- haxl-fxtra/src/Okta/Haxl.hs
- okta-client/cli/Main.hs
- okta-client/okta-client.cabal
- okta-client/src/Okta/Class.hs
- okta-client/src/Okta/Eval.hs
- okta-client/src/Okta/Request.hs
- okta-client/src/Okta/Types.hs
- okta-sync/okta-sync.cabal
- okta-sync/okta-sync.js
- okta-sync/src/Futurice/App/Okta.hs
- okta-sync/src/Futurice/App/Okta/API.hs
- okta-sync/src/Futurice/App/Okta/IndexPage.hs
- okta-sync/src/Futurice/App/Okta/Logic.hs
- okta-sync/src/Futurice/App/Okta/Markup.hs
> Update peoples information in Okta and add way to create users based

- proxy-types/src/Futurice/App/Proxy/API.hs
Problem: Prox integrations were failing
> Competence has been reworded to skill

- README.md
- lambdacss/src/LambdaCSS/Printer.hs
- library-app/src/Futurice/App/Library/Types/ItemType.hs
- mega-repo-tool/src/Futurice/App/MegaRepoTool/Lambda.hs
- planmill-proxy/src/Futurice/App/PlanMillProxy/Logic.hs
- planmill-proxy/src/Futurice/App/PlanMillProxy/Logic/Common.hs
- proxy-app/src/Servant/Excel.hs
- servant-binary-tagged/servant-binary-tagged.cabal
- servant-binary-tagged/src/Servant/Binary/Tagged.hs
- sisosota-app/sisosota-app.cabal
> Clean up few deprecated things, unnecessary imports and add mentions

- reports-app/src/Futurice/App/Reports/PowerUser.hs
> Extended report

- reports-app/src/Futurice/App/Reports/UtzChart.hs
mark uncertainly because of missing hours
> Modify chart to add dashes to last 4 months of the current year to
